data:
  train_dir: "/root/svdd_torch/data/train_dir"
  ntp: 10
  array_length: 32
  test_size: 0.3
---
train:
  pretrain: True
  batch_size: 64
  optimizer: 'adam'
  lr: 0.0001
  epochs: 15
  lr_milestone: 50
  weight_decay: 0.5e-6
  n_jobs_dataloader: 0
---
ae:
  lr: 0.0001
  epochs: 10
  optimizer: 'sgd'
  lr_milestone: 50
  batch_size: 64
  weight_decay: 0.5e-3
  normal_class: 3
  n_jobs_dataloader: 0
---
log:
  chkpt_dir: 'chkpt'
  log_dir: 'logs'
---
deepsvdd:
  objective: 'one-class'
  nu: 0.1